// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCl55ZBoXsDkMgCgi3rkLN34_lpy0L9Ecc',
    appId: '1:323552489384:android:9b6bbfa7e25db34357f79d',
    messagingSenderId: '323552489384',
    projectId: 'mot3lqat-mbc33',
    authDomain: 'mot3lqat-mbc33.firebaseapp.com',
    storageBucket: 'mot3lqat-mbc33.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl55ZBoXsDkMgCgi3rkLN34_lpy0L9Ecc',
    appId: '1:323552489384:android:9b6bbfa7e25db34357f79d',
    messagingSenderId: '323552489384',
    projectId: 'mot3lqat-mbc33',
    authDomain: 'mot3lqat-mbc33.firebaseapp.com',
    storageBucket: 'mot3lqat-mbc33.appspot.com',

  );




}
// TODO Implement this library.